spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
        username: root
        password: your-password

#jpa-settings
    jpa:
        hibernate:
            ddl-auto: create